id: AC0DA2E0B
title: Summary of Striking the Vital Point in Three Statements
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:58:49.278685
  last_modified_at: 2022-03-01 05:58:49.278692
