id: AC0DA2E0B
title: The Three Statements that Strike the Vital Point
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:58:49.281931
  last_modified_at: 2022-03-01 05:58:49.281935
